apiVersion: v2
name: matter-ai-enterprise
description: Helm chart to deploy Matter AI Code Review Backend for Enterprise
type: application
icon: https://matterai.so/favicon.png
appVersion: 0.1.60
version: 0.1.60
maintainers:
  - name: MatterAI
    email: support@matterai.so
