{{- range $componentName, $component := .Values.components }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $component.deployment.name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "gravity.labels" $ | nindent 4 }}
spec:
  replicas: {{ $component.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ $component.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ $component.deployment.name }}
    spec:
      {{- if eq $componentName "gravityAgent" }}
      serviceAccountName: {{ $.Values.rbac.serviceAccount.name }}
      {{- end }}
      {{- with $.Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $component.deployment.name }}
          image: "{{ $component.deployment.image.repository }}:{{ $component.deployment.image.tag }}"
          imagePullPolicy: {{ $component.deployment.image.pullPolicy }}
          {{- with $component.deployment.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $component.deployment.env }}
          env:
            {{- range $key, $value := . }}
            - name: {{ $key }}
              {{- if kindIs "map" $value }}
              {{- toYaml $value | nindent 14 }}
              {{- else }}
              value: {{ $value | quote }}
              {{- end }}
            {{- end }}
          {{- end }}
          {{- with $component.deployment.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $component.deployment.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with $component.deployment.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}