{{- if .Values.rbac.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "gravity.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.rbac.clusterRole.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "gravity.labels" . | nindent 4 }}
rules:
{{ toYaml .Values.rbac.clusterRole.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.rbac.clusterRoleBinding.name }}
  labels:
    {{- include "gravity.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.rbac.clusterRole.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
{{- end }}