global:
  namespace: "gravity-cloud"
  storageClass: "standard"
  nodeSelector: []

components:
  gravityWave:
    deployment:
      name: gravity-wave
      replicas: 1
      image:
        repository: gravitycloud/gravity-wave
        tag: latest
        pullPolicy: Always
      resources:
        requests:
          memory: "512Mi"
          cpu: "512m"
        limits:
          memory: "2048Mi"
          cpu: "1000m"
      env:
        GRAVITY_API_KEY:
          valueFrom:
            secretKeyRef:
              name: gravity-wave-secrets
              key: gravity-api-key
        GRAVITY_API_URL: ""
        GRAVITY_SOCKET_URL: ""
        POSTGRES_HOST: "postgres-gravity-wave-service"
        POSTGRES_USER: ""
        POSTGRES_PASSWORD:
          valueFrom:
            secretKeyRef:
              name: postgres-wave-secrets
              key: postgres-password
        GITHUB_APP_ID:
          valueFrom:
            secretKeyRef:
              name: gravity-wave-secrets
              key: github-app-id
        GITHUB_WEBHOOK_SECRET:
          valueFrom:
            secretKeyRef:
              name: gravity-wave-secrets
              key: github-webhook-secret
        GITHUB_CLIENT_ID:
          valueFrom:
            secretKeyRef:
              name: gravity-wave-secrets
              key: github-client-id
        GITHUB_CLIENT_SECRET:
          valueFrom:
            secretKeyRef:
              name: gravity-wave-secrets
              key: github-client-secret
        GITHUB_PRIVATE_KEY: # this is base64 encoded
          valueFrom:
            secretKeyRef:
              name: gravity-wave-secrets
              key: github-private-key
    service:
      name: gravity-wave-service
      type: ClusterIP
      port: 8080
      targetPort: 8080
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      hosts:
        - host: gravity-wave.example.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: gravity-wave-tls
          hosts:
            - gravity-wave.example.com

  postgres:
    deployment:
      name: postgres-gravity-wave
      replicas: 1
      image:
        repository: postgres
        tag: latest
        pullPolicy: IfNotPresent
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "1000m"
      env:
        POSTGRES_DB: ""
        POSTGRES_USER: ""
        POSTGRES_PASSWORD:
          valueFrom:
            secretKeyRef:
              name: postgres-wave-secrets
              key: postgres-password
      volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
          subPath: postgres
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-gravity-wave-pvc
    service:
      name: postgres-gravity-wave-service
      type: ClusterIP
      port: 5432
      targetPort: 5432

persistence:
  postgres:
    name: postgres-gravity-wave-pvc
    size: "1Gi"
    accessMode: ReadWriteOnce

secrets:
  gravityWave:
    name: gravity-wave-secrets
    data:
      gravity-api-key: ""
      github-app-id: ""
      github-webhook-secret: ""
      github-client-id: ""
      github-client-secret: ""
      github-private-key: ""
  postgres:
    name: postgres-wave-secrets
    data:
      postgres-password: ""