{{- if .Values.secrets }}
{{- range $component, $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "gravity.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := $secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}